// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR5s0OuRT-e_dGJavYuOkTs6kFmcjznOk',
    appId: '1:1036903929504:web:f76be0219d3d9b447cdbc5',
    messagingSenderId: '1036903929504',
    projectId: 'chat-8b708',
    authDomain: 'chat-8b708.firebaseapp.com',
    databaseURL: 'https://chat-8b708-default-rtdb.firebaseio.com',
    storageBucket: 'chat-8b708.appspot.com',
    measurementId: 'G-CJJK13XL5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6D_7yLcOxvQKFjRAUwD9g1-1vwnm1rGA',
    appId: '1:1036903929504:android:337a1fe19d7da9bf7cdbc5',
    messagingSenderId: '1036903929504',
    projectId: 'chat-8b708',
    databaseURL: 'https://chat-8b708-default-rtdb.firebaseio.com',
    storageBucket: 'chat-8b708.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS_snOXCAyvRv7Pa-JBHAlBHdX_ntx3I8',
    appId: '1:1036903929504:ios:a2c5c0ddd7ea71d67cdbc5',
    messagingSenderId: '1036903929504',
    projectId: 'chat-8b708',
    databaseURL: 'https://chat-8b708-default-rtdb.firebaseio.com',
    storageBucket: 'chat-8b708.appspot.com',
    iosClientId: '1036903929504-tivsoc01rfocekhaf9o3bs6ch84l7c2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.training',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS_snOXCAyvRv7Pa-JBHAlBHdX_ntx3I8',
    appId: '1:1036903929504:ios:a2c5c0ddd7ea71d67cdbc5',
    messagingSenderId: '1036903929504',
    projectId: 'chat-8b708',
    databaseURL: 'https://chat-8b708-default-rtdb.firebaseio.com',
    storageBucket: 'chat-8b708.appspot.com',
    iosClientId: '1036903929504-tivsoc01rfocekhaf9o3bs6ch84l7c2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.training',
  );
}
